# Generated by Django 2.2.5 on 2019-09-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_services_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='status',
            field=models.IntegerField(choices=[(1, 'Em andamento'), (2, 'Aprovado'), (3, 'Recusado'), (4, 'Finalizado')], default=1, verbose_name='Status'),
        ),
    ]
